---
# yamllint disable rule:line-length
name: Build Qt
# yamllint disable-line rule:truthy
on:
    push:
        paths:
            - tablet_qt/tools/build_qt.py
            - .github/workflows/build-qt.yml
jobs:
    build-qt:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - name: Qt prerequisites
              run: |
                  set -xe
                  sudo apt-get -y build-dep qt5-default
                  sudo apt-get -y install libxcb-xinerama0-dev
                  sudo apt-get -y install libdrm-dev libxcb-glx0-dev
            - name: Pip install
              run: |
                  set -xe
                  python -m venv ${HOME}/venv
                  source ${HOME}/venv/bin/activate
                  python -VV
                  python -m site
                  python -m pip install -U pip
                  echo dumping pre-installed packages
                  python -m pip freeze
                  echo installing pip packages
                  pip install cardinal_pythonlib
                  pip install distro
            - name: Build Qt
              run: |
                  source ${HOME}/venv/bin/activate
                  export CAMCOPS_QT_BASE_DIR=${HOME}/qt_local_build
                  cd tablet_qt/tools
                  ./build_qt.py --build_linux_x86_64
