---
# yamllint disable rule:line-length
name: Build and install Linux packages
# yamllint disable-line rule:truthy
on:
    push:
        paths:
            - '**.py'
            - .github/workflows/build-and-install-packages.yml
            - .github/workflows/scripts/build_packages.sh
            - .github/workflows/scripts/change_apt_mirror.sh
            - server/tools/MAKE_LINUX_PACKAGES.py
            - server/requirements-deb.txt
            - server/requirements-rpm.txt
jobs:
    build-and-install-package:
        strategy:
            matrix:
                # NumPy 1.21 incompatible with python 3.10
                # For the time being we're on 1.21.5 (see setup.py)
                # NumPy >= 1.22 incompatible with python 3.7
                python-version: [3.7, 3.8, 3.9]
                # LTS versions
                os: [ubuntu-20.04, ubuntu-22.04]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Change apt mirror
              run: |
                  set -eux -o pipefail
                  ${GITHUB_WORKSPACE}/.github/scripts/change_apt_mirror.sh
            - name: Build and install debian package
              run: |
                  set -eux -o pipefail
                  ${GITHUB_WORKSPACE}/.github/scripts/build_packages.sh
                  echo installing debian package
                  server/tools/REINSTALL_DEBIAN_PACKAGE.sh
                  echo checking packages for conflicts
                  /usr/share/camcops/venv/bin/pip check
