---
# yamllint disable rule:line-length
name: C++ tests
# yamllint disable-line rule:truthy
on:
    push:
        paths:
            - '**.cpp'
            - '**.h'
            - .github/scripts/add_apt_sources.sh
            - .github/scripts/change_apt_mirror.sh
            - .github/scripts/cpp_tests.sh
            - .github/workflows/cpp-tests.yml
            - tablet_qt/qt_version.txt
            - tablet_qt/tools/build_qt.py

jobs:
    cpp-tests:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - name: Install Qt
              run: |
                  set -euxo pipefail
                  cd ${HOME}
                  wget https://github.com/ucam-department-of-psychiatry/camcops/releases/download/qtbuild/qt.tgz
                  # Remove home/runner from paths
                  tar -xvzf qt.tgz --strip-components=2
                  ls
                  ls qt_local_build
            - name: Ubuntu prerequisites
              run: |
                  set -eux -o pipefail
                  ${GITHUB_WORKSPACE}/.github/scripts/change_apt_mirror.sh
                  ${GITHUB_WORKSPACE}/.github/scripts/add_apt_sources.sh
                  sudo apt-get -y install \
                  autoconf \
                  automake \
                  bison \
                  build-essential \
                  ccache \
                  cmake \
                  flex \
                  git \
                  gperf \
                  libass-dev \
                  libdrm-dev \
                  libegl1-mesa-dev \
                  libfontconfig1-dev \
                  libfreetype6-dev \
                  libgnutls28-dev \
                  libmp3lame-dev \
                  libnss3-dev \
                  libpulse-dev \
                  libsdl2-dev \
                  libtool \
                  libva-dev \
                  libvdpau-dev \
                  libvorbis-dev \
                  libx11-xcb-dev \
                  '^libxcb.*-dev' \
                  libxcomposite-dev \
                  libxcursor-dev \
                  libxdamage-dev \
                  libxi-dev \
                  libxkbcommon-dev \
                  libxkbcommon-x11-dev \
                  libxrandr-dev \
                  libxrender-dev \
                  meson \
                  ninja-build \
                  nodejs \
                  pkg-config \
                  texinfo \
                  wget \
                  yasm \
                  zlib1g-dev \
                  clang \
                  libatspi2.0-dev \
                  libbluetooth-dev \
                  libclang-13-dev \
                  libclang-14-dev \
                  libclang-15-dev \
                  libcups2-dev \
                  libfreetype6-dev \
                  libhunspell-dev \
                  libopengl-dev \
                  libts-dev \
                  libunwind-dev \
                  libx11-dev \
                  libxext-dev \
                  libxfixes-dev \
                  libxkbfile-dev \
                  libxshmfence1 \
                  libxshmfence-dev \
                  llvm \
                  python3

            - uses: actions/setup-python@v5
              with:
                  python-version: 3.8

            - name: C++ tests
              run: |
                  set -eux -o pipefail
                  export CAMCOPS_QT6_BASE_DIR=${HOME}/qt_local_build
                  xvfb-run --auto-servernum ${GITHUB_WORKSPACE}/.github/scripts/cpp_tests.sh
