---
# yamllint disable rule:line-length
name: C++ tests
# yamllint disable-line rule:truthy
on:
    push:
        paths:
            - '**.cpp'
            - '**.h'
            - .github/scripts/add_apt_sources.sh
            - .github/scripts/change_apt_mirror.sh
            - .github/scripts/cpp_tests.sh
            - .github/workflows/cpp-tests.yml
            - tablet_qt/qt_version.txt
            - tablet_qt/tools/build_qt.py

env:
    # Keep in sync with tablet_qt/qt_version.txt. We check this further down.
    QT_VERSION: 6.5.3
jobs:
    cpp-tests:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - name: Qt version check
              run: |
                  set -euxo pipefail
                  test "${{ env.QT_VERSION }}" == "$(cat ${GITHUB_WORKSPACE}/tablet_qt/qt_version.txt)"
            - name: Install Qt
              uses: jurplel/install-qt-action@v3
              with:
                  version: ${{ env.QT_VERSION }}
                  arch: gcc_64
                  modules: qtmultimedia
            - name: Ubuntu prerequisites
              run: |
                  set -eux -o pipefail
                  ${GITHUB_WORKSPACE}/.github/scripts/change_apt_mirror.sh
                  ${GITHUB_WORKSPACE}/.github/scripts/add_apt_sources.sh
                  sudo apt-get -y install \
                  libxcb-icccm4 \
                  libxcb-xkb1 \
                  libxcb-icccm4 \
                  libxcb-image0 \
                  libxcb-render-util0 \
                  libxcb-randr0 \
                  libxcb-keysyms1 \
                  libxcb-xinerama0 \
                  libxcb-xinput-dev \
                  libxcb-cursor0 \
                  xvfb \
                  x11-xserver-utils \
                  ccache

            - uses: actions/setup-python@v5
              with:
                  python-version: 3.8

            - name: Build SQL Cipher
              # And OpenSSL, Eigen
              run: |
                  set -eux -o pipefail
                  python -m venv ${HOME}/venv
                  source ${HOME}/venv/bin/activate
                  python -m pip install -U pip
                  echo dumping pre-installed packages
                  python -m pip freeze
                  echo installing pip packages
                  python -m pip install cardinal_pythonlib
                  python -m pip install distro
                  export CAMCOPS_QT6_BASE_DIR=${RUNNER_WORKSPACE}
                  cd tablet_qt/tools
                  # Build openssl and Qt
                  ./build_qt.py --build_linux_x86_64 --no_build_qt --no_build_ffmpeg

            - name: C++ tests
              run: |
                  set -eux -o pipefail
                  xvfb-run --auto-servernum ${GITHUB_WORKSPACE}/.github/scripts/cpp_tests.sh
