---
# yamllint disable rule:line-length
name: C++ tests
# yamllint disable-line rule:truthy
on:
    push:
        paths:
            - '**.cpp'
            - '**.h'
            - .github/scripts/add_apt_sources.sh
            - .github/scripts/change_apt_mirror.sh
            - .github/scripts/cpp_tests.sh
            - .github/workflows/cpp-tests.yml
            - tablet_qt/qt_version.txt
            - tablet_qt/tools/build_qt.py

jobs:
    cpp-tests:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - name: Install Qt
              run: |
                  set -euxo pipefail
                  cd ${RUNNER_WORKSPACE}
                  wget https://github.com/ucam-department-of-psychiatry/camcops/releases/download/qtbuild/qt.tgz
                  tar -xvzf qt.tgz
                  ls
                  ls qt_local_build
            - name: Ubuntu prerequisites
              run: |
                  set -eux -o pipefail
                  ${GITHUB_WORKSPACE}/.github/scripts/change_apt_mirror.sh
                  ${GITHUB_WORKSPACE}/.github/scripts/add_apt_sources.sh
                  sudo apt-get -y install \
                  libxcb-icccm4 \
                  libxcb-xkb1 \
                  libxcb-icccm4 \
                  libxcb-image0 \
                  libxcb-render-util0 \
                  libxcb-randr0 \
                  libxcb-keysyms1 \
                  libxcb-xinerama0 \
                  libxcb-xinput-dev \
                  libxcb-cursor0 \
                  xvfb \
                  x11-xserver-utils

            - uses: actions/setup-python@v5
              with:
                  python-version: 3.8

            - name: C++ tests
              run: |
                  set -eux -o pipefail
                  export CAMCOPS_QT6_BASE_DIR=${RUNNER_WORKSPACE}/qt_local_build
                  xvfb-run --auto-servernum ${GITHUB_WORKSPACE}/.github/scripts/cpp_tests.sh
