---
# yamllint disable rule:line-length
name: Launch CherryPy
# yamllint disable-line rule:truthy
on:
    push:
        paths:
            - '**.py'
            - .github/scripts/create_config_file.sh
            - .github/scripts/python_setup.sh
jobs:
    pip-install-and-tests:
        strategy:
            matrix:
                python-version: [3.8, 3.9, "3.10"]
                # LTS versions
                os: [ubuntu-20.04, ubuntu-22.04]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Launch CherryPy
              run: |
                  set -euxo pipefail

                  ${GITHUB_WORKSPACE}/.github/scripts/python_setup.sh
                  source ${HOME}/venv/bin/activate
                  export CAMCOPS_CONFIG_FILE="${HOME}/camcops.cfg"
                  ${GITHUB_WORKSPACE}/.github/scripts/create_config_file.sh
                  SSL_CERTIFICATE = ${HOME}/test.crt
                  SSL_PRIVATE_KEY = ${HOME}/test.key
                  openssl req -new -newkey rsa:4096 -nodes -keyout ${SSL_PRIVATE_KEY} -out ${SSL_CERTIFICATE} -subj "/C=GB/ST=Cambridgeshire/L=Cambridge/O=University of Cambridge/CN=localhost"
                  sed -i "s|SSL_CERTIFICATE =|SSL_CERTIFICATE = ${SSL_CERTIFICATE}|" ${CAMCOPS_CONFIG_FILE}
                  sed -i "s|SSL_PRIVATE_KEY =|SSL_PRIVATE_KEY = ${SSL_PRIVATE_KEY}|" ${CAMCOPS_CONFIG_FILE}
                  camcops_server serve_cherrypy &
