---
# yamllint disable rule:line-length
name: Launch CherryPy
# yamllint disable-line rule:truthy
on:
    push:
        paths:
            - '**.py'
            - .github/scripts/create_config_file.sh
            - .github/scripts/python_setup.sh
jobs:
    pip-install-and-tests:
        strategy:
            matrix:
                python-version: [3.8, 3.9, "3.10"]
                # LTS versions
                os: [ubuntu-20.04, ubuntu-22.04]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Launch CherryPy
              run: |
                  set -euxo pipefail

                  ${GITHUB_WORKSPACE}/.github/scripts/python_setup.sh
                  source ${HOME}/venv/bin/activate
                  export CAMCOPS_CONFIG_FILE="${HOME}/camcops.cfg"
                  ${GITHUB_WORKSPACE}/.github/scripts/create_config_file.sh
                  camcops_server serve_cherrypy
