---
# yamllint disable rule:line-length
name: Pip install and tests
# yamllint disable-line rule:truthy
on:
    push:
        paths:
            - '**.py'
            - .github/scripts/change_apt_mirror.sh
            - .github/scripts/create_config_file.sh
            - .github/scripts/mysql_local_setup.sh
            - .github/scripts/python_setup.sh
            - .github/workflows/pip-install-and-tests.yml
jobs:
    pip-install-and-tests:
        strategy:
            matrix:
                python-version: [3.8, 3.9, "3.10"]
                # LTS versions
                os: [ubuntu-20.04, ubuntu-22.04]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Set up MySQL
              run: |
            - name: Change apt mirror
              run: |
                  set -eux -o pipefail
                  ${GITHUB_WORKSPACE}/.github/scripts/change_apt_mirror.sh
            - name: Pip install and tests
              run: |
                  set -eux -o pipefail
                  # Install wkhtmltopdf on headless ubuntu 18 vps
                  # https://gist.github.com/lobermann/ca0e7bb2558b3b08923c6ae2c37a26ce
                  # 429 = Too many requests. Unfortunately wget doesn't read the
                  # Retry-after header so just wait 5 minutes
                  wget --retry-on-http-error=429 --waitretry=300 --tries=20 https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb
                  sudo apt-get -y install fontconfig libxrender1 xfonts-75dpi xfonts-base
                  sudo dpkg -i wkhtmltox_0.12.6-1.bionic_amd64.deb
                  ${GITHUB_WORKSPACE}/.github/scripts/python_setup.sh
                  source ${HOME}/venv/bin/activate
                  echo checking packages for conflicts
                  python -m pip check
                  echo installing vulnerability checker
                  python -m pip install safety
                  echo checking packages for vulnerabilities
                  # All of these vulnerabilities look either harmless or very low risk
                  # 51668 sqlalchemy fix in 2.0 beta, we don't log Engine.URL()
                  #       https://github.com/sqlalchemy/sqlalchemy/issues/8567
                  # 52495 setuptools fix in 65.5.1, we'll be careful not to
                  #       install malicious packages.
                  safety check --full-report --ignore=51668 --ignore=52495
                  echo running pre-commit checks
                  pre-commit run --all-files
                  ${GITHUB_WORKSPACE}/.github/scripts/create_config_file.sh
                  echo running tests
                  cd server/camcops_server
                  pytest -v
                  echo testing database upgrade / downgrade
                  python -m pip install pymysql
                  camcops_server upgrade_db --config ${CAMCOPS_CONFIG_FILE} --show_sql_only
                  camcops_server upgrade_db --config ${CAMCOPS_CONFIG_FILE}
                  # WARNING: Current Alembic v1.0.0 bug in downgrading with as_sql=True; may fail
                  # camcops_server dev_downgrade_db --config ${CAMCOPS_CONFIG_FILE} --destination_db_revision 0001 --confirm_downgrade_db --show_sql_only
                  camcops_server dev_downgrade_db --config ${CAMCOPS_CONFIG_FILE} --destination_db_revision 0001 --confirm_downgrade_db
                  camcops_server upgrade_db --config ${CAMCOPS_CONFIG_FILE} --show_sql_only
                  camcops_server upgrade_db --config ${CAMCOPS_CONFIG_FILE}
