---
name: Tests run on push
# yamllint disable-line rule:truthy
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python: [3.6, 3.7, 3.8, 3.9]
        steps:
            - name: Check out repository code
              uses: actions/checkout@v2
            - run: echo "${{ github.repository }} cloned."
            - name: List files in the repository
              run: |
                ls ${{ github.workspace }}
            - run: echo "This job's status is ${{ job.status }}."
