---
# yamllint disable rule:line-length

name: Tests run on push
# yamllint disable-line rule:truthy
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python: [3.6, 3.7, 3.8, 3.9]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  set -xe
                  python -VV
                  python -m site
                  python -m pip install -U pip
                  echo dumping GitHub-installed packages
                  python -m pip freeze
                  echo working around GitHub-installed package conflicts
                  # yamllint disable-line rule:line-length
                  sudo apt-get install python3-testresources python3-cairo --yes --no-install-recommends
                  echo installing pip packages
                  python -m pip install -e server/.
                  echo checking packages for conflicts
                  python -m pip check
                  echo installing vulnerability checker
                  python -m pip install safety
                  echo checking packages for vulnerabilities
                  safety check --full-report
                  echo checking python for style and errors
                  flake8 --config=setup.cfg server/camcops_server

            - run: echo "This job's status is ${{ job.status }}."
