---
# yamllint disable rule:line-length
name: Report missing client translations
# yamllint disable-line rule:truthy
on:
    push:
        paths:
            - .github/scripts/python_setup.sh
            - .github/scripts/report_missing_client_translations.sh
            - .github/workflows/report-missing-client-translations.yml
            - tablet_qt/**

jobs:
    report-missing-client-translations:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: "3.10"
            - name: Report missing client translations
              run: |
                  set -euxo pipefail
                  ${GITHUB_WORKSPACE}/.github/scripts/python_setup.sh
                  ${GITHUB_WORKSPACE}/.github/scripts/report_missing_client_translations.sh
